
package introsde.client.adapterClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdapterService", targetNamespace = "http://ws.adapter.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdapterService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSong", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.client.adapterClient.GetSong")
    @ResponseWrapper(localName = "getSongResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.client.adapterClient.GetSongResponse")
    @Action(input = "http://ws.adapter.introsde/AdapterService/getSongRequest", output = "http://ws.adapter.introsde/AdapterService/getSongResponse")
    public List<String> getSong();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuote", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.client.adapterClient.GetQuote")
    @ResponseWrapper(localName = "getQuoteResponse", targetNamespace = "http://ws.adapter.introsde/", className = "introsde.client.adapterClient.GetQuoteResponse")
    @Action(input = "http://ws.adapter.introsde/AdapterService/getQuoteRequest", output = "http://ws.adapter.introsde/AdapterService/getQuoteResponse")
    public List<String> getQuote();

}
